# Generated by Django 4.0.8 on 2024-05-04 16:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('mail', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=225)),
                ('registr_data', models.DateTimeField(default=django.utils.timezone.now)),
                ('sold', models.IntegerField()),
                ('contact_mail', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('region', models.CharField(max_length=225)),
                ('allowNotifications', models.BooleanField()),
                ('instagram', models.CharField(max_length=225)),
                ('telegram', models.CharField(max_length=225)),
                ('products', models.CharField(max_length=225)),
                ('image', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('code', models.IntegerField(default=316516)),
                ('price', models.IntegerField()),
                ('country', models.CharField(max_length=225)),
                ('type', models.CharField(max_length=225)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.CharField(max_length=225)),
                ('description', models.CharField(max_length=225)),
                ('images', models.CharField(max_length=225)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickbuyer.user')),
            ],
        ),
    ]
